Aim: To implement the random forest algorithm and evaluated the model performance using approach metrics
Name : Vaishnavi Sandokar(CS24D007)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path="/content/drive/MyDrive/ML /Gaming and Mental Health.csv"
df=pd.read_csv(path)
df.head(5)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   record_id                         1000 non-null   object 
 1   age                               1000 non-null   int64  
 2   gender                            1000 non-null   object 
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   object 
 5   primary_game                      1000 non-null   object 
 6   gaming_platform                   1000 non-null   object 
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   object 
 9   sleep_disruption_frequency        1000 non-null   object 
 10  academic_work_performance         1000 non-null   object 
 11  grades_gpa                        754 non-null    float64
 12  work_pr

In [ ]:
df.describe()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
count,1000.000000,1000.000000,1000.000000,754.000000,674.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.475000,6.151400,5.738100,2.518037,5.394659,1.513400,6.945900,3.872000,7.654500,105.219730,5.796000
std,4.116105,2.867194,1.441213,0.872312,2.898742,1.432212,1.805027,2.091409,3.751954,113.886768,3.775532
min,13.000000,0.500000,3.000000,1.010000,1.000000,0.000000,0.700000,1.000000,0.000000,0.100000,1.000000
25%,18.000000,4.100000,4.800000,1.760000,3.000000,0.400000,5.700000,2.000000,5.000000,32.592500,3.000000
50%,20.000000,6.000000,5.700000,2.530000,5.000000,1.100000,7.000000,4.000000,8.000000,66.405000,5.000000
75%,22.000000,8.025000,6.600000,3.280000,8.000000,2.100000,8.200000,5.000000,10.400000,126.242500,8.000000
max,35.000000,15.100000,9.000000,4.000000,10.000000,8.900000,11.500000,10.000000,16.700000,499.270000,20.000000


In [ ]:
df.shape

(1000, 27)

In [ ]:
df.columns

Index(['record_id', 'age', 'gender', 'daily_gaming_hours', 'game_genre',
       'primary_game', 'gaming_platform', 'sleep_hours', 'sleep_quality',
       'sleep_disruption_frequency', 'academic_work_performance', 'grades_gpa',
       'work_productivity_score', 'mood_state', 'mood_swing_frequency',
       'withdrawal_symptoms', 'loss_of_other_interests',
       'continued_despite_problems', 'eye_strain', 'back_neck_pain',
       'weight_change_kg', 'exercise_hours_weekly', 'social_isolation_score',
       'face_to_face_social_hours_weekly', 'monthly_game_spending_usd',
       'years_gaming', 'gaming_addiction_risk_level'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.True_

In [ ]:
df=[df.isnull().any(axis=1)]

In [ ]:
df = pd.read_csv(path)
X = df.drop(columns=['gaming_addiction_risk_level'])
y = df['gaming_addiction_risk_level']

In [ ]:
X

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,False,True,True,False,6.8,3.7,7,1.3,383.70,3
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,False,0.4,8.5,2,10.7,46.64,1
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,True,False,True,1.8,7.1,5,3.2,100.81,6
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,True,False,True,True,0.2,5.2,4,9.1,51.60,7
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,False,0.5,6.1,4,4.5,32.57,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,GD0996,15,Female,8.6,Strategy,Age of Empires,PC,4.1,Very Poor,Always,...,False,True,True,True,1.9,7.5,6,2.4,426.54,3
996,GD0997,18,Male,5.4,MMO,Elder Scrolls Online,Multi-platform,6.5,Fair,Never,...,False,False,True,False,2.1,7.7,1,10.9,83.71,7
997,GD0998,23,Male,7.3,RPG,Skyrim,PC,3.9,Insomnia,Rarely,...,True,False,False,True,0.5,8.1,5,6.7,88.60,5
998,GD0999,18,Male,3.1,Strategy,StarCraft II,Console,8.2,Fair,Sometimes,...,False,False,False,False,0.8,8.4,1,12.7,22.02,8


In [ ]:
X.head

<bound method NDFrame.head of     record_id  age  gender  daily_gaming_hours     game_genre  \
0      GD0001   17    Male                11.1   Mobile Games   
1      GD0002   21    Male                 3.0           MOBA   
2      GD0003   23    Male                 7.6            FPS   
3      GD0004   20  Female                 7.2            RPG   
4      GD0005   18    Male                 6.8  Battle Royale   
..        ...  ...     ...                 ...            ...   
995    GD0996   15  Female                 8.6       Strategy   
996    GD0997   18    Male                 5.4            MMO   
997    GD0998   23    Male                 7.3            RPG   
998    GD0999   18    Male                 3.1       Strategy   
999    GD1000   29    Male                 3.5            RPG   

             primary_game gaming_platform  sleep_hours sleep_quality  \
0          Clash of Clans              PC          3.7     Very Poor   
1                  Dota 2              PC          7.2          Fair   
2                   CS:GO  Multi-platform          4.4          Fair   
3                  Skyrim  Multi-platform          5.1          Fair   
4            Apex Legends              PC          3.4          Poor   
..                    ...             ...          ...           ...   
995        Age of Empires              PC          4.1     Very Poor   
996  Elder Scrolls Online  Multi-platform          6.5          Fair   
997                Skyrim              PC          3.9      Insomnia   
998          StarCraft II         Console          8.2          Fair   
999        Cyberpunk 2077  Multi-platform          7.4          Good   

    sleep_disruption_frequency  ... loss_of_other_interests  \
0                    Sometimes  ...                   False   
1                       Rarely  ...                   False   
2                        Often  ...                    True   
3                        Often  ...                    True   
4                        Never  ...                   False   
..                         ...  ...                     ...   
995                     Always  ...                   False   
996                      Never  ...                   False   
997                     Rarely  ...                    True   
998                  Sometimes  ...                   False   
999                  Sometimes  ...                   False   

     continued_despite_problems  eye_strain back_neck_pain weight_change_kg  \
0                          True        True          False              6.8   
1                         False       False          False              0.4   
2                          True       False           True              1.8   
3                         False        True           True              0.2   
4                         False       False          False              0.5   
..                          ...         ...            ...              ...   
995                        True        True           True              1.9   
996                       False        True          False              2.1   
997                       False       False           True              0.5   
998                       False       False          False              0.8   
999                       False       False          False              0.0   

     exercise_hours_weekly  social_isolation_score  \
0                      3.7                       7   
1                      8.5                       2   
2                      7.1                       5   
3                      5.2                       4   
4                      6.1                       4   
..                     ...                     ...   
995                    7.5                       6   
996                    7.7                       1   
997                    8.1                       5   
998                    8.4                       1   
999                    9

In [ ]:
X = pd.get_dummies(X,dtype = int)


In [ ]:
X

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,withdrawal_symptoms,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,...,mood_state_Excited,mood_state_Irritable,mood_state_Normal,mood_state_Restless,mood_state_Withdrawn,mood_swing_frequency_Daily,mood_swing_frequency_Never,mood_swing_frequency_Often,mood_swing_frequency_Rarely,mood_swing_frequency_Sometimes
0,17,11.1,3.7,1.25,NaN,True,False,True,True,False,...,0,0,0,0,0,0,1,0,0,0
1,21,3.0,7.2,3.75,2.0,False,False,False,False,False,...,0,1,0,0,0,0,0,1,0,0
2,23,7.6,4.4,NaN,9.0,True,True,True,False,True,...,0,1,0,0,0,0,0,0,1,0
3,20,7.2,5.1,1.62,2.0,True,True,False,True,True,...,0,0,0,0,1,1,0,0,0,0
4,18,6.8,3.4,2.44,NaN,True,False,False,False,False,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,15,8.6,4.1,2.96,NaN,True,False,True,True,True,...,0,0,0,1,0,0,0,0,0,1
996,18,5.4,6.5,3.42,NaN,False,False,False,True,False,...,0,0,0,0,0,0,0,1,0,0
997,23,7.3,3.9,NaN,3.0,True,True,False,False,True,...,0,0,0,0,1,1,0,0,0,0
998,18,3.1,8.2,1.03,NaN,False,False,False,False,False,...,0,0,1,0,0,0,0,0,1,0


In [ ]:
X.head()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,withdrawal_symptoms,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,...,mood_state_Excited,mood_state_Irritable,mood_state_Normal,mood_state_Restless,mood_state_Withdrawn,mood_swing_frequency_Daily,mood_swing_frequency_Never,mood_swing_frequency_Often,mood_swing_frequency_Rarely,mood_swing_frequency_Sometimes
0,17,11.1,3.7,1.25,NaN,True,False,True,True,False,...,0,0,0,0,0,0,1,0,0,0
1,21,3.0,7.2,3.75,2.0,False,False,False,False,False,...,0,1,0,0,0,0,0,1,0,0
2,23,7.6,4.4,NaN,9.0,True,True,True,False,True,...,0,1,0,0,0,0,0,0,1,0
3,20,7.2,5.1,1.62,2.0,True,True,False,True,True,...,0,0,0,0,1,1,0,0,0,0
4,18,6.8,3.4,2.44,NaN,True,False,False,False,False,...,0,0,0,0,0,1,0,0,0,0


In [ ]:
X.shape

(1000, 1084)

In [ ]:
X.columns

Index(['age', 'daily_gaming_hours', 'sleep_hours', 'grades_gpa',
       'work_productivity_score', 'withdrawal_symptoms',
       'loss_of_other_interests', 'continued_despite_problems', 'eye_strain',
       'back_neck_pain',
       ...
       'mood_state_Excited', 'mood_state_Irritable', 'mood_state_Normal',
       'mood_state_Restless', 'mood_state_Withdrawn',
       'mood_swing_frequency_Daily', 'mood_swing_frequency_Never',
       'mood_swing_frequency_Often', 'mood_swing_frequency_Rarely',
       'mood_swing_frequency_Sometimes'],
      dtype='object', length=1084)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,test_size=0.3,random_state = 42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=100,n_jobs=-1,max_depth=5,oob_score=True,random_state=42)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
y_pred=rf_classifier.predict(X_test)

In [ ]:
print('Confusion Matrix')
cm= confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

Confusion Matrix
[[ 21   0   8   8]
 [  9 148  38   1]
 [ 17   0   4   7]
 [  5   0   0  34]]


In [ ]:
print(accuracy_score(y_pred,y_test))

0.69


In [ ]:
print(accuracy_score)

<function accuracy_score at 0x7e7ca35de020>


In [ ]:
rf=RandomForestClassifier(random_state=42,n_jobs=1)
params = {
    'max_depth':[2,3,5,10,20],
    'min_samples_leaf':[5,10,20,50,100,200],
    'n_estimators':[10,25,30,50,100,200]
}

In [ ]:
grid_search=GridSearchCV(estimator=rf,param_grid=params,cv = 4,n_jobs=-1,verbose=1,scoring='accuracy')
grid_search.fit(X_train,y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits


GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [ ]:
grid_search.best_score_

np.float64(0.6671428571428571)